<?php
echo $_SERVER['PHP_SELF'];
echo $_SERVER['GATEWAY_INTERFACE'];
echo $_SERVER['SERVER_ADDR'];
echo $_SERVER['SERVER_NAME'];
echo $_SERVER['SERVER_SOFTWARE'];
echo $_SERVER['SERVER_PROTOCOL'];
echo $_SERVER['REQUEST_METHOD'];
echo $_SERVER['REQUEST_TIME'];
echo $_SERVER['QUERY_STRING'];
echo $_SERVER['HTTP_ACCEPT'];
echo $_SERVER['HTTP_ACCEPT_CHARSET'];
echo $_SERVER['HTTP_HOST'];
echo $_SERVER['HTTP_REFERER'];
echo $_SERVER['HTTPS'];
echo $_SERVER['REMOTE_ADDR'];
echo $_SERVER['REMOTE_HOST'];
echo $_SERVER['REMOTE_PORT'];
echo $_SERVER['SCRIPT_FILENAME'];
echo $_SERVER['SERVER_ADMIN'];
echo $_SERVER['SERVER_PORT'];
echo $_SERVER['SERVER_SIGNATURE'];
echo $_SERVER['PATH_TRANSLATED'];
echo $_SERVER['SCRIPT_NAME'];
echo $_SERVER['SCRIPT_URI'];
?>